### ISSUE TITLE
Disable new button on nestedForm

### ISSUE THREAD

**Issue by naingwin** [z-song/laravel-admin#2259] opened 2018-08-01 19:19 UTC
- Laravel Version: 5.6.*
- PHP Version:
- Laravel-admin: 1.5.*

### Description:
How can I disable "New" button on "hasMany" nestedForm?

**Comment by pei-lun** [comment] 2018-09-15 13:51
Duplicate of #1027

**Closed** 2019-04-30 15:19 UTC
Labels: wontfix
