### ISSUE TITLE
I am trying to check an image file exist or not from another website. But I am failed

### ISSUE THREAD

**Issue by laziestcoder** [z-song/laravel-admin#2441] opened 2018-09-05 03:24 UTC
Hello!

I am trying to check an image file exist or not from another website.

like $url = 'www.xyz.com/Pictures/xyz.jpg'.
if( checkFunction ($url) ) {
return true;
}else{
return false;
}

But my problem is I can not figure out what is the 'Check Function'. I have tried file, file_get_content, file_exist, get_headers. But I am failed.

Can anyone help me?

**Comment by jxlwqq** [comment] 2018-09-05 03:32
The issue is not about Laravel-admin. Please close it.
Try this code please:
```
$image_url = 'www.xyz.com/Pictures/xyz.jpg';
$ch = curl_init($image_url);
curl_setopt($ch, CURLOPT_NOBODY, true);
curl_exec($ch);
$retcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
curl_close($ch);
// $retcode >= 400 -> not found, $retcode = 200, found.
if ($retcode == 200) {
    return true;
}
```

**Closed** 2018-09-05 05:49 UTC

**Comment by laziestcoder** [comment] 2018-09-05 05:51
ok thank you :)
