### ISSUE TITLE
Not able to update 1.7.10

### ISSUE THREAD

**Issue by azinkey** [z-song/laravel-admin#4405] opened 2020-02-27 05:32 UTC
- Laravel Version: 6.2
- PHP Version: 7.2
- Laravel-admin: 1.7.9

composer require encore/laravel-admin install 1.7.9,  I tried to update it to 1.7.10 but it fails

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package encore/laravel-admin 1.7.10 exists as encore/laravel-admin[1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.x-dev, 1.5.x-dev, dev-analysis-L3MwLP, dev-develop, dev-master, v1.1.6, v1.2.10, v1.2.6, v1.2.8, v1.2.9, v1.3.3, v1.3.4, v1.4.1, v1.4.4, v1.4.5, v1.4.6, v1.5.10, v1.5.11, v1.5.12, v1.5.13, v1.5.14, v1.5.15, v1.5.16, v1.5.17, v1.5.18, v1.5.19, v1.5.5, v1.5.6, v1.5.7, v1.5.8, v1.5.9, v1.6.0, v1.6.1, v1.6.10, v1.6.11, v1.6.12, v1.6.13, v1.6.14, v1.6.15, v1.6.2, v1.6.3, v1.6.4, v1.6.5, v1.6.6, v1.6.7, v1.6.8, v1.6.9, v1.7.0, v1.7.1, v1.7.2, v1.7.3, v1.7.4, v1.7.5, v1.7.6, v1.7.7, v1.7.8, v1.7.9] but these are rejected by your constraint.

Steps To Reproduce:
composer update

**Comment by Bluefitdev** [comment] 2020-02-27 22:49
Duplicate of #4397

**Comment by z-song** [comment] 2020-03-02 15:59
Fixed now， try to update later.

**Closed by z-song** 2020-03-02 15:59 UTC
